  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [ python ]
        args: [ --fix, --exit-non-zero-on-fix ]